# Generated by Django 3.0.9 on 2020-09-21 18:49

import app_ccf.encoder
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ccf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('manual_edit', 'Manual Edit')], max_length=40)),
                ('initial_app_json', django.contrib.postgres.fields.jsonb.JSONField(encoder=app_ccf.encoder.ApplicationEncoder)),
                ('final_app_json', django.contrib.postgres.fields.jsonb.JSONField(encoder=app_ccf.encoder.ApplicationEncoder)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ccf.Application')),
            ],
        ),
    ]
